apiVersion: v1
kind: Service
metadata:
  name: back-node-port-service
spec:
  type: NodePort
  selector:
    app: apiimg
  ports:
    - protocol: TCP
      nodePort: 30008 #This is the port exposed by the node -- Send your resquest here to verify
      port: 3010 #This is the port exposed by the container
      targetPort: 3001 #This is the port used by node to talk to container