apiVersion: v1
kind: Service
metadata:
  name: front-node-port-service
spec:
  type: NodePort
  selector:
    app: webimg
  ports:
    - protocol: TCP
      nodePort: 30009
      port: 3000
      targetPort: 3000